# Generated by Django 5.1.3 on 2024-11-15 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taggedimage',
            name='image',
            field=models.ImageField(upload_to='tagged_images/'),
        ),
    ]
